site_name: Template Operator
docs_dir: content
site_url: https://docs.stakater.com/template-operator-docs/
repo_url: https://github.com/stakater/template-operator-docs
edit_uri: blob/main/content/
theme:
  favicon: assets/images/favicon.svg

strict: true
validation:
  links:
    anchors: warn

extra:
  version:
    provider: mike
    default: latest

nav:
  - Overview:
      - index.md
      - overview/key-features.md
      - overview/use-cases.md
  - Concepts:
      - concepts/architecture.md
      - concepts/terminology.md
      - Templates:
          - concepts/templates/template.md
          - concepts/templates/template-instance.md
          - concepts/templates/cluster-template-instance.md
  - Getting Started:
      - Installation:
          - getting-started/installation/overview.md
          - getting-started/installation/openshift.md
          - getting-started/installation/kubernetes.md
  - Guides:
      - Templates:
          - guides/templates/deploying-templates.md
          - guides/templates/distributing-manifests.md
          - guides/templates/copying-resources.md
          - guides/templates/copying-resources-2.md
          - guides/templates/distributing-secrets-using-sealed-secret-template.md
          - guides/templates/deploying-private-helm-charts.md
          - guides/templates/template-default-params.md
          - guides/templates/resource-sync-by-tgi.md
  - Reference:
      - reference/api.md
      - reference/metrics.md
  - Troubleshooting: troubleshooting.md
  - Release Notes: release-notes.md
  - EULA: eula.md